name: verify

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: pnpm/action-setup@v6
        with:
          version: 10.8.1

      - uses: actions/setup-node@v6
        with:
          cache: pnpm
          node-version: 24

      - run: pnpm install --frozen-lockfile
      - run: pnpm verify
